### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: cannot change name of view column "draw" to "avghome"

### ISSUE THREAD

**Issue by gunnartorfis** [syxolk/euro2016#22]
I'm getting this error when I pull the latest commit. I know I'm a bit late to the party.. but any clue?

Looking forward to use this app completely during the world cup of 2018! Perhaps you could make some money from it? Make a website that allows people to create groups for friends, etc. Give me some endpoints from an API and I'll make an iOS app from it ;)

**Comment by syxolk** [comment]
Try to delete all the views (NOT the tables) and then restart the server.

**Comment by gunnartorfis** [comment]
Still the same. I removed all the views and ran npm install and then node index.js again.

`Unhandled rejection SequelizeDatabaseError: cannot change name of view column "draw" to "avghome"
  at [object Object].Query.formatError (/var/www/gunnartorfis.me/euro16/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
  at [object Object].<anonymous> (/var/www/gunnartorfis.me/euro16/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
  at emitOne (events.js:77:13)
  at [object Object].emit (events.js:169:7)
  at [object Object].Query.handleError (/var/www/gunnartorfis.me/euro16/node_modules/pg/lib/query.js:108:8)
  at [object Object].<anonymous> (/var/www/gunnartorfis.me/euro16/node_modules/pg/lib/client.js:171:26)
  at emitOne (events.js:77:13)
  at [object Object].emit (events.js:169:7)
  at Socket.<anonymous> (/var/www/gunnartorfis.me/euro16/node_modules/pg/lib/connection.js:109:12)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:531:20)`
